from numpy cimport ndarray

cpdef object numpyToVtkImageData(ndarray np)

cpdef object simpleITKToVTK(object img)

cdef class SisypheImage:

    cdef object _sitk_image
    cdef object _itk_image
    cdef object _vtk_image
    cdef ndarray _numpy_array
    cdef dict _attr

    cdef object _toSimpleITK(self, object img)
    cdef void _updateImages(self)
    cdef void _updateNumpyFromSITKImage(self)
    cdef void _updateVTKImageFromNumpy(self)
    cdef void _updateITKImageFromNumpy(self)

    cpdef bint hasITKImage(self)
    cpdef void allocate(self, object matrix, str datatype)
    cpdef void copyFromSITKImage(self, object img)
    cpdef void copyFromVTKImage(self, object img)
    cpdef void copyFromITKImage(self, object img)
    cpdef void copyFromANTSImage(self, object img)
    cpdef void copyFromNumpyArray(self, ndarray img, object spacing, object origin, object direction=*, bint defaultshape=*)
    cpdef void copyFromPillowImage(self, object img, int slc, int orient=*)
    cpdef void copyFromNibabelImage(self, object img)
    cpdef object copyToSITKImage(self)
    cpdef object copyToVTKImage(self)
    cpdef object copyToITKImage(self)
    cpdef object copyToANTSImage(self, str dtype=*, bint direction=*)
    cpdef ndarray copyToNumpyArray(self, bint defaultshape=*)
    cpdef object copyToNibabelImage(self)
    cpdef object copyToPillowImage(self, int slc, int orient=*, bint rgb=*, object wmin=*, object wmax=*)
    cpdef tuple cast(self, str datatype)
    cpdef object copy(self)
    cpdef object copyComponent(self, int c=*)
    cpdef object getSITKImage(self)
    cpdef void setSITKImage(self, object img)
    cpdef object getVTKImage(self)
    cpdef object getITKImage(self)
    cpdef ndarray getNumpy(self, bint defaultshape=*)
    cpdef object getSize(self)
    cpdef int getWidth(self)
    cpdef int getHeight(self)
    cpdef int getDepth(self)
    cpdef object getSpacing(self)
    cpdef bint hasSameSpacing(self, object img, int decimals=*)
    cpdef void setSpacing(self, float sx, float sy, float sz)
    cpdef double getVoxelVolume(self)
    cpdef int getNumberOfVoxels(self)
    cpdef int getNumberOfVoxelsInXYPlane(self)
    cpdef int getNumberOfVoxelsInXZPlane(self)
    cpdef int getNumberOfVoxelsInYZPlane(self)
    cpdef bint isIsotropic(self, double tol=*)
    cpdef bint isAnisotropic(self, double tol=*)
    cpdef bint isThickAnisotropic(self, double tol=*, double thickness=*)
    cpdef int getNative2DOrientation(self)
    cpdef tuple getNative2DOrientationAsString(self)
    cpdef tuple getCenter(self)
    cpdef tuple getFieldOfView(self, object decimals=*)
    cpdef bint hasSameFieldOfView(self, object img, int decimals=*)
    cpdef str getDatatype(self)
    cpdef bint isIntegerDatatype(self)
    cpdef bint isUInt8Datatype(self)
    cpdef bint isInt8Datatype(self)
    cpdef bint isUInt16Datatype(self)
    cpdef bint isInt16Datatype(self)
    cpdef bint isUInt32Datatype(self)
    cpdef bint isInt32Datatype(self)
    cpdef bint isUInt64Datatype(self)
    cpdef bint isInt64Datatype(self)
    cpdef bint isFloatDatatype(self)
    cpdef bint isFloat32Datatype(self)
    cpdef bint isFloat64Datatype(self)
    cpdef object getDatatypeAs(self, str lib=*)
    cpdef int getNumberOfComponentsPerPixel(self)
    cpdef bint isMulticomponent(self)
    cpdef int getNumberOfDimensions(self)
    cpdef tuple getDirections(self)
    cpdef object getFirstVectorDirection(self)
    cpdef object getSecondVectorDirection(self)
    cpdef object getThirdVectorDirection(self)
    cpdef void setDirections(self, object direction=*)
    cpdef object getMemorySize(self, str rep=*)
    cpdef void setDefaultOrigin(self)
    cpdef void setOrigin(self, object origin=*)
    cpdef void setOriginToCenter(self)
    cpdef tuple getOrigin(self)
    cpdef bint isDefaultOrigin(self)
    cpdef bint hasSameOrigin(self,object origin)
    cpdef object getWorldCoordinatesFromVoxelCoordinates(self, object p)
    cpdef object getVoxelCoordinatesFromWorldCoordinates(self, object p)
    cpdef double getValueAtContinuousIndex(self, object p, bint world=*, int order=*)
    cpdef void fillWith(self, double v=*)
    cpdef void fillSlicesWith(self, object sl, double v=*, int orient=*)
    cpdef bint isEmpty(self)
    cpdef bint isEmptyArray(self)
    cpdef bint sliceIsEmpty(self, object index, int orient)
    cpdef object getMask(self, str algo=*, str morpho=*, int niter=*, int kernel=*, str fill=*, object c=*)
    cpdef object getThresholdingMask(self, double threshold=*, str op=*, object c=*)
    cpdef object getROI(self, double threshold=*, str op=*, object c=*)
    cpdef object getMask2(self, str algo=*, int morphoiter=*, int kernel=*, bint objstep=*, object c=*)
    cpdef object getMaskROI(self, str algo=*, str morpho=*, int niter=*, int kernel=*, str fill=*, object c=*)
    cpdef object getMaskROI2(self, str algo=*, int morphoiter=*, int kernel=*, bint objstep=*, object c=*)
    cpdef void replaceNanInfValues(self, double nan=*, double posinf=*, double neginf=*)
    cpdef object getRelabeled(self, dict cross)
    cpdef object getNonZeroMask(self, object c=*)
    cpdef tuple getCentroid(self, bint binary=*, str ref=*, object c=*)
    cpdef double getBackgroundThreshold(self, str algo=*, object c=*)
    cpdef object getCrop(self, object c)
    cpdef ndarray getBoundingBox(self, double threshold=*, int margin=*, bint blobs=*)
    cpdef ndarray getLocalMaxima(self, double threshold)
    cpdef object getProjection(self, str d=*, double thickness=*, str func=*, str output=*, object emask=*)
    cpdef object getCroppedProjection(self, int slc, str d=*, double thickness=*, str func=*, str output=*, object emask=*)
    cpdef dict sliceHeadSurface(self, str orient=*)
    cpdef object removeNeckSlices(self, double f=*)
    cpdef tuple getReorient(self, double f=*)
    cpdef double noiseEstimate(self)
    cpdef object getMean(self, object mask=*, object c=*)
    cpdef object getMedian(self, object mask=*, object c=*)
    cpdef object getStd(self, object mask=*, object c=*)
    cpdef object getMin(self, bint nonzero=*, object c=*)
    cpdef object getMax(self, object mask=*, object c=*)
    cpdef object getArgmax(self, object mask=*)
    cpdef object getRange(self, object mask=*, object c=*)
    cpdef object getPercentile(self, object perc=*, object mask=*, object c=*)
    cpdef object getKurtosis(self, object mask=*, object c=*)
    cpdef object getSkewness(self, object mask=*, object c=*)
    cpdef tuple getHistogram(self, object mask=*, int bins=*, object range=*, bint density=*, int c=*)
    cpdef dict getStatistics(self, object mask=*, int c=*)
    cpdef int getNumberOfNonZero(self, int c=*)
    cpdef object getComponentMean(self, object c=*)
    cpdef object getComponentStd(self, object c=*)
    cpdef object getComponentMin(self, object c=*)
    cpdef object getComponentMax(self, object c=*)
    cpdef object getComponentRange(self, object c=*)
    cpdef object getComponentMedian(self, object c=*)
    cpdef object getComponentPercentile(self, int perc=*, object c=*)
    cpdef object getComponentKurtosis(self, object c=*)
    cpdef object getComponentSkewness(self, object c=*)
    cpdef object getComponentArgmax(self)
    cpdef object getComponentArgmin(self, bint nonzero=*)
    cpdef object getComponentNumberOfNonZero(self, object c=*)
    cpdef object getComponentAllZero(self, object c=*)
    cpdef void flip(self, list axis)
    cpdef object getFlip(self, list axis)
    cpdef void standardizeIntensity(self, str method=*)
    cpdef object getStandardizeIntensity(self, str method=*)
    cpdef truncateIntensity(self, int centile=*, tuple outputrange=*, bint onlymax=*)
    cpdef object getTruncateIntensity(self, int centile=*, tuple outputrange=*, bint onlymax=*)
    cpdef void saveToNIFTI(self, str filename, bint compress=*)
    cpdef void saveToNRRD(self, str filename)
    cpdef void saveToMINC(self, str filename)
    cpdef void saveToVTK(self, str filename)
    cpdef void saveToJSON(self, str filename)
    cpdef void saveToNumpy(self, str filename)
    cpdef dict loadFromSisyphe(self, str filename)
    cpdef dict loadFromBrainVoyagerVMR(self, str filename)
    cpdef void loadFromFreeSurferMGH(self, str filename)
    cpdef void loadFromNIFTI(self, str filename, bint reorient=*)
    cpdef void loadFromNRRD(self, str filename)
    cpdef void loadFromMINC(self, str filename)
    cpdef void loadFromVTK(self, str filename)
    cpdef void loadFromNumpy(self, str filename)

cdef class SisypheBinaryImage(SisypheImage):

    cpdef void copyFromSITKImage(self, object img)
    cpdef void copyFromVTKImage(self, object img)
    cpdef void copyFromITKImage(self, object img)
    cpdef void copyFromANTSImage(self, object img)
    cpdef void copyFromNumpyArray(self, ndarray img, object spacing=*, object origin=*, object direction=*, bint defaultshape=*)
    cpdef void setSITKImage(self, object img)